backend:
  name: git-gateway
  branch: main

media_folder: images
public_folder: /images

locale: zh_Hant

collections:
  - name: handbook
    label: 員旅手冊內容
    files:
      - name: index
        label: 手冊主頁（index.html）
        file: index.html
        fields:
          - label: 網頁原始碼
            name: body
            widget: code
            default_language: html
            output_code_only: true
